### ISSUE TITLE
４章 P50 表3　表記がおかしい？

### ISSUE THREAD

**Issue by tnaoto** [hamakn/software-design-2012-04#2]
P50　表3の「DEAのスペック」において

項目：コア数　
ノード：４Gバイト

と表記されている。

コア数あたり４Gバイトのメモリ割り当てなのか、コア数が４つということなのか？

たぶん後者だろうけど・・・。

**Comment by hamakn** [comment]
ありがとうございます。後者が正しいです。

誤: コア数 4Gバイト
正: コア数 4
